CREATE SCHEMA IF NOT EXISTS VOLKSEVIS;
CREATE TABLE IF NOT EXISTS VOLKSEVIS.CITY (CITYID int(11) NOT NULL AUTO_INCREMENT,CITYNAME varchar(45) DEFAULT NULL,ACTIVE int(11) DEFAULT NULL,PRIMARY KEY (CITYID)) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;
INSERT INTO VOLKSEVIS.CITY VALUES (1,'Hyderabad',1),(2,'Banglore',1),(3,'Vishakapatnam',1),(4,'Vijayawada',1),(5,'Guntur',1);